services:
  bbac-agents:
    build: .
    ports:
      - "17180:3000"
    volumes:
      # 将本地的 agents.txt 挂载到容器内的 /app/data/agents.txt
      - ./agents.txt:/app/data/agents.txt:rw
    environment:
      - NODE_ENV=production
      - DOCKER=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
